In [1]:
import torch

def func(x,y):
    return sum(x**3+x*y*y + x**3*y+y**6)

inputs = (torch.ones(3),torch.ones(3))

print(torch.autograd.functional.hessian(func,inputs))

def func2(x):
    return sum(x**3)

inputs = torch.ones(3)

print(torch.autograd.functional.hessian(func2,inputs))
inputs2 = inputs.clone().detach().requires_grad_(True)
out = func2(inputs2)
out.backward()
print(inputs2.grad)

((tensor([[12.,  0.,  0.],
        [ 0., 12.,  0.],
        [ 0.,  0., 12.]]), tensor([[5., 0., 0.],
        [0., 5., 0.],
        [0., 0., 5.]])), (tensor([[5., 0., 0.],
        [0., 5., 0.],
        [0., 0., 5.]]), tensor([[32.,  0.,  0.],
        [ 0., 32.,  0.],
        [ 0.,  0., 32.]])))
tensor([[6., 0., 0.],
        [0., 6., 0.],
        [0., 0., 6.]])
tensor([3., 3., 3.])


In [2]:
import torch 
def func(x):
    return x**2

def func2(x,y):
    return (x**2)*y
inputs = torch.ones(3)
inputs2 = (torch.ones(3),torch.ones(3))
out = torch.autograd.functional.jacobian(func,inputs) # []
out2 = torch.autograd.functional.jacobian(func2,inputs2) # []
print(out)
print(out2)

tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])
(tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]]), tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))


In [3]:
import torch 
def func(x):
    return x**3

def func2(x,y):
    return (x**3)*y
inputs = torch.ones(3,requires_grad=True)
inputs2 = (torch.ones(3),torch.ones(3))

out2 = torch.autograd.functional.jacobian(func2, inputs2) # []
# second = torch.autograd.grad(out[0][0], inputs, create_graph=True)
def second_derivative_of_vector_func(func, inputs, wrt=None):
    # func - func that takes vector input and return vector
    # inputs - vector input or cartage of vectors for func
    # wrt - if inputs are cartage, that wrt needs to choose the derivative option [[xx,xy],[yx,yy]]
    jacobian = torch.autograd.functional.jacobian(func, inputs, create_graph = True) # []
    print(jacobian)
    if wrt is not None:
        jacobian = jacobian[wrt[0]]
        last_shape = inputs[wrt[0]].shape[0]
    else:
        last_shape = inputs.shape[0]
    second = torch.zeros((jacobian.shape[0], jacobian.shape[1], last_shape))
    for x in range(jacobian.shape[0]):
        for y in range(jacobian.shape[1]):
            second[x,y] = torch.autograd.grad(jacobian[x,y], inputs, create_graph=True)[0]
    return second
out = second_derivative_of_vector_func(func,inputs)
out2 = second_derivative_of_vector_func(func2,inputs2,wrt=[0,0])
# second1 = torch.autograd.grad(out[0][1], inputs, create_graph=True)
# out.backward()
# print(second)
# print(second1)

# print(inputs.grad)
print(out)
print(out2)

tensor([[3., 0., 0.],
        [0., 3., 0.],
        [0., 0., 3.]], grad_fn=<ViewBackward>)
(tensor([[3., 0., 0.],
        [0., 3., 0.],
        [0., 0., 3.]], grad_fn=<ViewBackward>), tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], grad_fn=<ViewBackward>))


RuntimeError: One of the differentiated Tensors does not require grad

In [ ]:
torch.__version__

'1.8.1+cu102'