In [ ]:
import torch

def func(x,y):
    return sum(x**3+x*y*y + x**3*y+y**6)

inputs = (torch.ones(3),torch.ones(3))

print(torch.autograd.functional.hessian(func,inputs))

def func2(x):
    return sum(x**3)

inputs = torch.ones(3)

print(torch.autograd.functional.hessian(func2,inputs))
inputs2 = inputs.clone().detach().requires_grad_(True)
out = func2(inputs2)
out.backward()
print(inputs2.grad)

In [ ]:
import torch 
def func(x):
    return x**2

def func2(x,y):
    return (x**2)*y
inputs = torch.ones(3)
inputs2 = (torch.ones(3),torch.ones(3))
out = torch.autograd.functional.jacobian(func,inputs) # []
out2 = torch.autograd.functional.jacobian(func2,inputs2) # []
print(out)
print(out2)

In [ ]:
import torch 
def func(x):
    return x**3

def func2(x,y):
    return (x**3)*y
inputs = torch.ones(3,requires_grad=True)
inputs2 = (torch.ones(3),torch.ones(3))

out2 = torch.autograd.functional.jacobian(func2, inputs2) # []
# second = torch.autograd.grad(out[0][0], inputs, create_graph=True)
def second_derivative_of_vector_func(func, inputs, wrt=None):
    # func - func that takes vector input and return vector
    # inputs - vector input or cartage of vectors for func
    # wrt - if inputs are cartage, that wrt needs to choose the derivative option [[xx,xy],[yx,yy]]
    jacobian = torch.autograd.functional.jacobian(func, inputs, create_graph = True) # []
    print(jacobian)
    if wrt is not None:
        jacobian = jacobian[wrt[0]]
        last_shape = inputs[wrt[0]].shape[0]
    else:
        last_shape = inputs.shape[0]
    second = torch.zeros((jacobian.shape[0], jacobian.shape[1], last_shape))
    for x in range(jacobian.shape[0]):
        for y in range(jacobian.shape[1]):
            second[x,y] = torch.autograd.grad(jacobian[x,y], inputs, create_graph=True)[0]
    return second
out = second_derivative_of_vector_func(func,inputs)
# out2 = second_derivative_of_vector_func(func2,inputs2,wrt=[0,0])
# second1 = torch.autograd.grad(out[0][1], inputs, create_graph=True)
# out.backward()
# print(second)
# print(second1)

# print(inputs.grad)
print(out)
# print(out2)

In [43]:
import torch
x = torch.Tensor([2,3,4,0.2,0.4])
x.requires_grad_(True)
R = 0.1
Vr = 0.3
dt= 0.5

# 1 IIC [IICx,IICy,Vr*self.dt]
print(x)
print(torch.sin(x[2])*torch.Tensor([-1,0])+torch.cos(x[2])*torch.Tensor([0,1]))
# aux
print(torch.tensor([-torch.sin(x[2]),torch.cos(x[2])]))

tensor([2.0000, 3.0000, 4.0000, 0.2000, 0.4000], requires_grad=True)
tensor([ 0.7568, -0.6536], grad_fn=<AddBackward0>)
tensor([ 0.7568, -0.6536])


In [62]:
import torch
x = torch.Tensor([2,3,4,0.2,0.4])
x.requires_grad_(True)
R = 0.1
Vr = 0.3
dt= 0.5

# 2 IIC [IICx,IICy,Vr*self.dt]
print(x)
aux1 = torch.eye(3)
aux1[2,2]=0
aux2 = torch.zeros((3,3))
aux2[1,0] = 1
aux2[0,1] = -1
aux3 = torch.zeros((3,3))
aux3[2,2] = 1

# theta = 
out = torch.cos(x[2]*dt)*aux1+torch.sin(x[2]*dt)*aux2+aux3
print(out)


tensor([2.0000, 3.0000, 4.0000, 0.2000, 0.4000], requires_grad=True)
tensor([[-0.4161, -0.9093,  0.0000],
        [ 0.9093, -0.4161,  0.0000],
        [ 0.0000,  0.0000,  1.0000]], grad_fn=<AddBackward0>)


In [58]:
matrix = torch.tensor([[torch.cos(x[2]*dt),-torch.sin(x[2]*dt),  0],
                       [torch.sin(x[2]*dt), torch.cos(x[2]*dt),  0],
                       [        0,                       0,      1]])
matrix

tensor([[-0.4161, -0.9093,  0.0000],
        [ 0.9093, -0.4161,  0.0000],
        [ 0.0000,  0.0000,  1.0000]])

In [77]:
import torch
x = torch.Tensor([2,3,4,0.2,0.4])
x.requires_grad_(True)
R = 0.1
Vr = 0.3
dt= 0.5

print(x)
aux1 = torch.eye(3)
aux1[2,2]=0
aux2 = torch.zeros((3,3))
aux2[1,0] = 1
aux2[0,1] = -1
aux3 = torch.zeros((3,3))
aux3[2,2] = 1
IIC = x[:2]+R*(
                torch.sin(x[2])*torch.Tensor([-1,0])+
                torch.cos(x[2])*torch.Tensor([0,1]))

# aux1            
# 3 IIC [IICx,IICy,Vr*self.dt]
# theta = 
# out = torch.cos(x[2]*dt)*aux1+torch.sin(x[2]*dt)*aux2+aux3
print(IIC[0]*torch.Tensor([1,0,0])+IIC[1]*torch.Tensor([0,1,0])+Vr*dt*torch.Tensor([0,0,1]))
print(IIC*torch.Tensor([1,1,0])+Vr*dt*torch.Tensor([0,0,1]))

# torch.tensor([IIC,Vr*self.dt]

tensor([2.0000, 3.0000, 4.0000, 0.2000, 0.4000], requires_grad=True)
tensor([2.0757, 2.9346, 0.1500], grad_fn=<AddBackward0>)


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

In [79]:
import torch
aux1 = torch.eye(3)
aux1[2,2]=0
print("aux1",aux1)
aux2 = torch.zeros((3,3))
aux2[1,0] = 1
aux2[0,1] = -1
print("aux2",aux2)
aux3 = torch.zeros((3,3))
aux3[2,2] = 1
print("aux3",aux3)


aux1 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.]])
aux2 tensor([[ 0., -1.,  0.],
        [ 1.,  0.,  0.],
        [ 0.,  0.,  0.]])
aux3 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 1.]])
